### ISSUE TITLE
(help offer) Why is python-opentimestamps source copied in this project?

### ISSUE THREAD

**Issue by ankostis** [opentimestamps/opentimestamps-client#32]
Is there a reason for having the sources of [python-opentimestamps](/opentimestamps/python-opentimestamps) project are copied verbatim in this project under `python-opentimestamps/` folder?

- Is it a WIP for moving those sources out of this project, into a separate one, to be `pip install`ed?
- Is the separate project going to be dropped, and have all sources in this project?
- Why both projects do not have a `setup.py` script, and support proper executable command?
- Can I help in one of the above tasks?

**Comment by petertodd** [comment]
It's copied verbatim - specifically with git's subtree functionality - precisely because development of python-opentimestamps hasn't settled down to the point where we can give it a version number and start doing formal releases. That'll happen soon, but not quite yet; since it hasn't happened git subtrees are the best way to ensure we know _exactly_ what version of python-opentimestamps a given commit in the opentimestamps client is using.

**Comment by petertodd** [comment]
I'm happy to say this issue is now fixed, as of v0.5.0!

You can now install the client via PyPi:

    $ pip3 install opentimestamps-client
    $ ots stamp <your-file>

Easy!

Full announcement here: https://lists.opentimestamps.org/pipermail/ots-announce/2017-August/000005.html
