### ISSUE TITLE
ots in examples aren't stand alone executable

### ISSUE THREAD

**Issue by RCasatta** [opentimestamps/opentimestamps-client#4]
Considering the output
```
$ ./ots info examples/hello-world.txt.ots 
File sha256 hash: 03ba204e50d126e4674c005e04d82e84c21366780af1f43bd54a37816b6ab340
Timestamp:
ripemd160
...
```
Since the first operation of the path is ripemd160 while I got the file hash in sha256, could I verify the ots without the file `hello-world.txt`?

**Comment by petertodd** [comment]
The verify command has an option to provide a hash digest in place of the file; if you don't have the hash of the file in the form that the timestamp takes then yes, there's no way to verify it. The only way I could fix that would be to make the timestamp a DAG rather than a tree - a lot of extra complexity.

**Comment by petertodd** [comment]
Oh sorry! I just realized I misunderstood your question somewhat.

You're nearly correct, but the first operation _is_ SHA256, not RIPEMD160. The detached timestamp file format treats the first operation specially and stores it separately from the other operations. That's why the info command shows "FIle sha256 hash" - that's telling you that the first operation is a SHA256 on the file contents itself.
